version: '3'

services:
  node:
    container_name: ${DOCKER_PROJECT_NAME}_node
    env_file: .env.local
    image: node:20-bullseye
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: /bin/sh -c "
      npm i -g @quasar/cli &&
      echo 'npm version:' &&
      npm -v &&
      echo 'node version:' &&
      node -v &&
      echo '--------------' &&
      npm install &&
      quasar build"
